### ISSUE TITLE
`status` queryString doesn't work one `/api/claims?status=claimed`

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/boss-backend#12]
It just lists all the claims and not filter by status.
![screen shot 2017-05-18 at 12 20 46 am](https://cloud.githubusercontent.com/assets/8109774/26170743/1cc548ba-3b60-11e7-815c-f00bc67b7392.png)

**Comment by championswimmer** [comment]
valid bug, acepted. added bounty

**Comment by championswimmer** [comment]
done via https://github.com/coding-blocks/boss-backend/pull/14
