### ISSUE TITLE
Error while Logging In

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/boss-backend#137]
![screen shot 2018-06-15 at 3 54 12 pm](https://user-images.githubusercontent.com/29139786/41463537-6e5019c8-70b4-11e8-9147-53c7a70f6f80.png)
Not able to log in and got automatically logged out

**Comment by architkshk** [comment]
Same issue.

**Comment by gamemma** [comment]
you people can simply enter your username and password manually at the place of Username and Password.Then this issue will resolve.
