### ISSUE TITLE
Next Button Not disabled

### ISSUE THREAD

**Issue by sirjan13** [coding-blocks/boss-backend#16]
As we browse the leaderboard as the leaderboard ends the next button should be disabled but currently it takes us to a blank page with just the table headers

## **Last Page:**
![image](https://cloud.githubusercontent.com/assets/22820957/26374885/803c5230-4024-11e7-94c6-f822ef839908.png)

## **After the last page on clicking on Next(which should have been disabled at end of leaderboard):**
![image](https://cloud.githubusercontent.com/assets/22820957/26374941/b14043fa-4024-11e7-8e88-fe9ab504d4d4.png)

**Comment by sirjan13** [comment]
@championswimmer  please review

**Comment by abhishek97** [comment]
@sirjan13 yes definitely a mistake. do you want go ahead and fix it?

**Comment by championswimmer** [comment]
added bounty. anyone can go ahead and fix it

**Comment by abhishek97** [comment]
@championswimmer  Fixed In : #23
