### ISSUE TITLE
make a page about this project on lab.codingblocks.com

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss-backend#21]
check for reference how to add a new project - https://github.com/coding-blocks/lab.codingblocks.com/pull/7

**Comment by bhavyaagg** [comment]
@championswimmer added the page.

**Comment by bhavyaagg** [comment]
@championswimmer bhaiya please check the pull request coding-blocks/lab.codingblocks.com/pull/9

**Comment by prateekiiest** [comment]
@championswimmer , pls review my PR
I have updated links on the feature section.
If you say, I can start working on adding images to the blog posts too.
