### ISSUE TITLE
add an item on the navbar for showing open issues

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/boss-backend#26]
link to all open issues for BOSS = 
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3ABOSS+org%3Acoding-blocks  or

`https://github.com/issues?utf8=✓&q=is:open is:issue label:BOSS org:coding-blocks`

**Comment by mukulsaini** [comment]
@championswimmer is it required to make a separate page also for listing all the issues or just add the item to the navbar which will open this link= `https://github.com/issues?utf8=✓&q=is:open is:issue label:BOSS org:coding-blocks` ?
